version: "3.8"

services:
  # Database
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: django_automation_database

  # Django App
  app:
    build: .
    volumes:
      - .:/django
    env_file:
      - .env
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_automation
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
